"use client";

import Link from "next/link";
import { ArrowRight, CheckCircle2, ImagePlus, Search } from "lucide-react";
import { useState } from "react";
import { MapPicker } from "@/components/map/MapPicker";
import { EmptyState, LoadingState } from "@/components/ui";
import { VehicleCard } from "@/components/VehicleCard";
import type { LocationPoint, RouteMatch } from "@/types";

const nextDay = () => { const date = new Date(Date.now() + 2 * 86400000); date.setHours(7, 0, 0, 0); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); };

export function GoodsBookingFlow() {
  const [pickup, setPickup] = useState<LocationPoint>(); const [drop, setDrop] = useState<LocationPoint>();
  const [details, setDetails] = useState({ departureTime: nextDay(), goodsType: "PARCEL", weightKg: 10, quantity: 1, sizeDescription: "Small box", isFragile: false, requiresColdStorage: false, isHeavy: false, imageUrl: "" });
  const [matches, setMatches] = useState<RouteMatch[] | null>(null); const [recommended, setRecommended] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState("");
  const [booking, setBooking] = useState<{ id: string; pickupOtp: string; deliveryOtp: string } | null>(null);
  const change = (key: string, value: string | number | boolean) => setDetails((current) => ({ ...current, [key]: value }));
  const upload = async (file?: File) => { if (!file) return; const form = new FormData(); form.append("file", file); const response = await fetch("/api/uploads", { method: "POST", body: form }); const data = await response.json(); if (response.ok) change("imageUrl", data.url); else setError(data.error); };
  const search = async () => { if (!pickup || !drop) { setError("Select both pickup and drop on the map."); return; } setLoading(true); setError(""); setBooking(null); const payload = { ...details, departureTime: new Date(details.departureTime).toISOString(), pickup, drop }; const response = await fetch("/api/matches/goods", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); setMatches(data.matches || []); setRecommended(data.recommendedVehicle || ""); setError(data.error || ""); setLoading(false); };
  const book = async (match: RouteMatch) => { if (!pickup || !drop) return; setBusy(match.tripId); const response = await fetch("/api/bookings/goods", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...details, tripId: match.tripId, pickup, drop, paymentMethod: "UPI" }) }); const data = await response.json(); if (response.ok) setBooking(data.booking); else setError(data.error === "LoadMate login required" ? "Log in as a LoadMate to confirm this booking." : data.error); setBusy(""); };
  if (booking) return <div className="card mx-auto max-w-2xl text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-eco-50 text-eco-600"><CheckCircle2 className="h-8 w-8" /></span><p className="eyebrow mt-5">Goods space confirmed</p><h2 className="text-3xl font-black">Your load has a return ride.</h2><div className="mx-auto mt-4 grid max-w-sm grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-3"><small className="font-bold text-slate-500">Pickup OTP</small><strong className="block font-mono text-xl">{booking.pickupOtp}</strong></div><div className="rounded-xl bg-slate-50 p-3"><small className="font-bold text-slate-500">Delivery OTP</small><strong className="block font-mono text-xl">{booking.deliveryOtp}</strong></div></div><div className="mt-6 flex flex-col justify-center gap-3 sm:flex-row"><Link className="btn-primary" href={`/tracking/goods/${booking.id}`}>Track delivery <ArrowRight className="h-4 w-4" /></Link><Link className="btn-secondary" href="/dashboard/goods">View dashboard</Link></div></div>;
  return <div className="grid gap-7"><MapPicker pickup={pickup} drop={drop} onChange={(type, location) => type === "pickup" ? setPickup(location) : setDrop(location)} vehicles={matches?.map((m) => ({ ...m.from, label: `${m.vehicleType} · ${m.driverName}` }))} />
    <div className="card grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Field label="Departure"><input className="field" type="datetime-local" value={details.departureTime} onChange={(e) => change("departureTime", e.target.value)} /></Field><Field label="Goods type"><select className="field" value={details.goodsType} onChange={(e) => change("goodsType", e.target.value)}><option>PARCEL</option><option>GROCERIES</option><option>BOXES</option><option>FURNITURE</option><option>AGRICULTURE</option><option>MEDICINE</option></select></Field><Field label="Weight (kg)"><input className="field" type="number" min="0.1" value={details.weightKg} onChange={(e) => change("weightKg", Number(e.target.value))} /></Field><Field label="Quantity"><input className="field" type="number" min="1" value={details.quantity} onChange={(e) => change("quantity", Number(e.target.value))} /></Field><Field label="Size description"><input className="field" value={details.sizeDescription} onChange={(e) => change("sizeDescription", e.target.value)} /></Field><Field label="Goods photo"><label className="btn-secondary w-full cursor-pointer"><ImagePlus className="h-4 w-4" />{details.imageUrl ? "Photo uploaded" : "Upload photo"}<input className="hidden" type="file" accept="image/*" onChange={(e) => upload(e.target.files?.[0])} /></label></Field><div className="flex flex-wrap items-end gap-3">{[["isFragile","Fragile"],["requiresColdStorage","Cold"],["isHeavy","Heavy"]].map(([key,label]) => <label key={key} className="flex items-center gap-2 rounded-xl bg-slate-50 px-3 py-3 text-sm font-bold"><input type="checkbox" checked={Boolean(details[key as keyof typeof details])} onChange={(e) => change(key, e.target.checked)} />{label}</label>)}</div><button className="btn-primary self-end" onClick={search} disabled={loading}><Search className="h-4 w-4" /> Match goods space</button></div>
    {recommended && <p className="rounded-xl border border-brand-100 bg-brand-50 p-3 text-sm font-bold text-brand-800">Rule-based vehicle suggestion: <strong>{recommended.replaceAll("_", " ")}</strong>. Matches still respect capacity, permits, goods type and route detour.</p>}{error && <p className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error} {error.startsWith("Log in") && <Link className="underline" href="/login">Login here</Link>}</p>}{loading ? <LoadingState /> : matches && (matches.length ? <div className="grid gap-4"><div><p className="eyebrow">{matches.length} nearby-route match{matches.length !== 1 ? "es" : ""}</p><h2 className="section-title">Permitted return vehicles</h2></div>{matches.map((match) => <VehicleCard key={match.tripId} match={match} mode="goods" onBook={() => book(match)} busy={busy === match.tripId} />)}</div> : <EmptyState title="No permitted goods vehicle found" copy="The engine checked route proximity, detour, capacity, permit, goods type and cold-storage requirements." />)}
  </div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="label">{label}</span>{children}</label>; }
