"use client";

import { FormEvent, ReactNode, Suspense, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Boxes, Building2, Check, Eye, EyeOff, Truck, Users } from "lucide-react";
import { AuthShell } from "@/components/AuthShell";

const roles=[{id:"ROUTEMATE",title:"RouteMate",copy:"Book passenger return seats",icon:Users},{id:"LOADMATE",title:"LoadMate",copy:"Send goods on return routes",icon:Boxes},{id:"CAPTAIN",title:"Backhaul Captain",copy:"Post vehicle return trips",icon:Truck},{id:"MERCHANT",title:"Merchant",copy:"Manage repeat business loads",icon:Building2}] as const;
type Role=typeof roles[number]["id"];
export default function RegisterPage(){return <Suspense fallback={<AuthShell title="Create your account" copy="Loading secure registration…"><div className="h-64 animate-pulse rounded-2xl bg-slate-100"/></AuthShell>}><RegisterForm/></Suspense>}
function RegisterForm(){const params=useSearchParams();const router=useRouter();const requested=params.get("role") as Role|null;const [role,setRole]=useState<Role|undefined>(roles.some(r=>r.id===requested)?requested||undefined:undefined);const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [usernameStatus,setUsernameStatus]=useState<{available:boolean;suggestions:string[]}|null>(null);const [form,setForm]=useState({fullName:"",username:"",phone:"",email:"",password:"",confirmPassword:"",language:"en",otpMethod:"EMAIL"});
  useEffect(()=>{if(form.username.length<3){setUsernameStatus(null);return;}const timer=setTimeout(()=>fetch(`/api/auth/username?value=${encodeURIComponent(form.username)}`).then(r=>r.json()).then(setUsernameStatus),350);return()=>clearTimeout(timer)},[form.username]);
  const change=(key:string,value:string)=>setForm(f=>({...f,[key]:value}));
  const submit=async(e:FormEvent)=>{e.preventDefault();setError("");if(!role)return;if(form.password!==form.confirmPassword){setError("Passwords do not match");return;}if(usernameStatus&&!usernameStatus.available){setError("Choose an available username");return;}setBusy(true);const r=await fetch("/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,role})});const data=await r.json();setBusy(false);if(!r.ok){setError(data.error);return;}sessionStorage.setItem("backhaul_otp_hint",data.mockOtp||"");localStorage.setItem("backhaul_language",form.language);router.push(`/verify-otp?identifier=${encodeURIComponent(form.email)}`)};
  if(!role)return <AuthShell title="How will you use Backhaul?" copy="Choose an account type. You can still travel or send goods through separate accounts."><div className="grid gap-3 sm:grid-cols-2">{roles.map(item=><button key={item.id} onClick={()=>setRole(item.id)} className="rounded-2xl border border-slate-200 p-5 text-left transition hover:-translate-y-0.5 hover:border-brand-300 hover:bg-brand-50"><item.icon className="mb-5 h-7 w-7 text-brand-700"/><strong className="block text-lg">{item.title}</strong><span className="text-sm text-slate-500">{item.copy}</span></button>)}</div></AuthShell>;
  return <AuthShell title={`Create ${roles.find(r=>r.id===role)?.title} account`} copy="The selected language changes the visible site UI after registration."><button className="mb-5 text-sm font-bold text-brand-700" onClick={()=>setRole(undefined)}>← Change account type</button><form className="grid gap-4 sm:grid-cols-2" onSubmit={submit}><Field label="Full name"><input required className="field" value={form.fullName} onChange={e=>change("fullName",e.target.value)}/></Field><Field label="Username"><input required pattern="[a-zA-Z0-9_]{3,24}" className="field" value={form.username} onChange={e=>change("username",e.target.value)}/>{usernameStatus&&<div className={`mt-1 text-xs font-bold ${usernameStatus.available?"text-eco-700":"text-red-600"}`}>{usernameStatus.available?<span className="flex items-center gap-1"><Check className="h-3 w-3"/> Available</span>:<>Already used. Try: {usernameStatus.suggestions.map(s=><button type="button" className="ml-1 underline" onClick={()=>change("username",s)} key={s}>{s}</button>)}</>}</div>}</Field><Field label="Phone number"><input required inputMode="numeric" pattern="[6-9][0-9]{9}" maxLength={10} className="field" placeholder="10 digits, starts 6–9" value={form.phone} onChange={e=>change("phone",e.target.value.replace(/\D/g,""))}/></Field><Field label="Email"><input required type="email" className="field" value={form.email} onChange={e=>change("email",e.target.value)}/></Field><Field label="Password"><span className="relative block"><input required minLength={8} type={show?"text":"password"} pattern="(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9]).{8,}" title="8+ characters with uppercase, lowercase, number and special character" className="field !pr-10" value={form.password} onChange={e=>change("password",e.target.value)}/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-3.5 text-slate-400">{show?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></span><small className="text-[11px] text-slate-500">8+ chars: upper, lower, number, special</small></Field><Field label="Confirm password"><input required minLength={8} type="password" className="field" value={form.confirmPassword} onChange={e=>change("confirmPassword",e.target.value)}/></Field><Field label="Preferred language"><select className="field" value={form.language} onChange={e=>change("language",e.target.value)}><option value="en">English</option><option value="te">తెలుగు</option><option value="hi">हिन्दी</option></select></Field><Field label="OTP method"><select className="field" value={form.otpMethod} onChange={e=>change("otpMethod",e.target.value)}><option value="EMAIL">Email (mock)</option><option value="SMS">SMS (mock)</option></select></Field>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700 sm:col-span-2">{error}</p>}<button disabled={busy} className="btn-primary sm:col-span-2">{busy?"Creating account…":"Create account & verify OTP"}</button></form></AuthShell>}
function Field({label,children}:{label:string;children:ReactNode}){return <label><span className="label">{label}</span>{children}</label>}
